RAILS_ENV = "development" unless defined?(RAILS_ENV) #stub for dev
require 'rubygems'
require 'active_support'
require 'extensions/hash'
require 'shipsurance/shipsurance'
require 'shipsurance/base'
require 'shipsurance/response'
require 'shipsurance/claim_response'
require 'shipsurance/claim_status_response'
require 'shipsurance/record_shipment_response'
require 'shipsurance/void_record_shipment_response'
require 'shipsurance/validation_response'
require 'shipsurance/claim'
require 'shipsurance/claim_status'
require 'shipsurance/record_shipment'
require 'shipsurance/void_record_shipment'
require 'shipsurance/validation'
require 'shipsurance/person'
require 'shipsurance/address'


